<?php
$ticket = $this->getTicket();
?>
<h2><?php echo $this->escapeHtml($ticket->getSubject()); ?></h2>
<a href="<?php echo $this->getClosedChangeUrl($ticket); ?>"><?php echo $this->getClosedChangeLabel($ticket); ?></a>
<?php if($ticket->getClosed()): ?>
<h2>Can not reply to closed ticket!</h2>
<?php endif; ?>

<?php foreach($ticket->getReplies() as $reply): ?>
    <div>
        [<?php echo $reply->getCreatedAt(); ?>]
        <?php echo $reply->getAuthorName(); ?>
    </div>
    <div>- <?php echo $this->escapeHtml($reply->getMessage()); ?></div>
<?php endforeach; ?>